# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "npm"
  directory: "/home"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "03:00"
    timezone: "Asia/Tokyo"
- package-ecosystem: "npm"
  directory: "/playground"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "03:00"
    timezone: "Asia/Tokyo"
